### ISSUE TITLE
Enumerate all adapters

### ISSUE THREAD

**Issue by jp7677** [SveSop/nvtt#1]
Hi @SveSop, looking at
https://github.com/SveSop/nvtt/blob/2f4c15fa2dcefedf7dd610325cc31f9b53bc1898/nvtt.c#L57, it would be cool if you could enumerate over all available adapters (similar like https://github.com/jp7677/dxvk-nvapi/blob/master/src/sysinfo/nvapi_adapter_registry.cpp#L32) and print their properties. Dxvk used to return also software adapters like lavapipe. While not that useful for gaming (dxvk master does not return those anymore) having multiple adapters is a cool test case for alternative nvapi implementations :).

**Comment by SveSop** [comment]
Does this help in any way? [https://github.com/SveSop/nvtt/commit/092d0452e9545bc6f67da2d7dccfbcea9a50243d](https://github.com/SveSop/nvtt/commit/092d0452e9545bc6f67da2d7dccfbcea9a50243d)

A bit unsure about the "HDR Capabilities" and possible other stuff, since i only have 1 adapter to choose from, i cannot really do much testing for "others".

**Comment by jp7677** [comment]
Yes, that works, thanks, I'm seeing 2 adapters with DXVK 1.8 with recent Mesa.

**Comment by jp7677** [comment]
PS: I've changed the sources locally to do a 64bit build and removed the linking arguments, that way it's a bit simpler regarding dependencies on the host system. Let me know if you are interested in the details.

**Comment by jp7677** [comment]
PPS: Please also check the result of LoadLibrary, if `nvapi.dll`, or `nvapi64.dll` in my case cannot be found, your program just segfaults.

**Comment by SveSop** [comment]
Do you mean the 
```
[built-in options]
c_link_args = ['-static']
```
If so, i removed it, as it did not really do much since i dont link against any library anyway... i think :) 

Not really sure i see the need to build it as 64bit. Building 32bit makes sure it works on a 32bit wineprefix AND 64bit. Building 64bit would make it only work on 64bit prefixes. Not sure how important that is, but for such a simple proggy, it is not (imo) anything to really be gained by building it as 64bit, other than checking that the 64bit nvapi functions also work. Maybe build both for completeness sake? Ie. `nvtt.exe` and `nvtt64.exe`?

Will check the loadlibrary function. Just lazy writing i guess... Might need a little fiddling if building 32/64 bit versions i guess.

**Comment by SveSop** [comment]
95b5144eb26ae0aca0a48f405c0844cd5c6a1598 should fail with a message if nvapi is not present instead of segfault.

**Comment by jp7677** [comment]
> If so, i removed it, as it did not really do much since i dont link against any library anyway... i think :)

Yes, exactly. Thanks.

> Not really sure i see the need to build it as 64bit.

No worries about this. I would prefer 64bit since I don't have all that 32bit stuff on my host since I'm building inside docker. Though your argument is the better one ;).

> [95b5144](https://github.com/SveSop/nvtt/commit/95b5144eb26ae0aca0a48f405c0844cd5c6a1598) should fail with a message if nvapi is not present instead of segfault.

You are now calling LoadLibary twice. It does the job, but it better to use the result of the first call if it succeeded. E.g. like https://github.com/jp7677/dxvk-nvapi/blob/master/src/sysinfo/vulkan.cpp#L8

**Comment by SveSop** [comment]
I was overcomplicating this, as i thought it was the loading that segfaulted, and not the "call with the pointer"...
2672f569cfe33fb6365f7a6eaa8fb6c7e1d84844
Hopefully a bit leaner :)

**Comment by jp7677** [comment]
You have to this one by one, something like this:

```c
HMODULE module = LoadLibrary("nvapi.dll");
if (!module) {
  printf("nvapi.dll could not be found or loaded!\n");
  return 1;
}

NvQueryInterface = (void*)GetProcAddress(module, "nvapi_QueryInterface");
if(!NvQueryInterface){
  printf("nvAPI interface not available!\n");
  return 1;
}

...

FreeLibrary(module);
return 0;
```

**Comment by jp7677** [comment]
> I was overcomplicating this, as i thought it was the loading that segfaulted,

Loading was indeed wat went wrong

**Comment by jp7677** [comment]
LoadLibrary returns NULL when the library could not be found, e.g. the file does not exists. Using NULL with GetProcAddress segfaults, hence the check before  calling GetProcAddress.

PS: Sorry, hit the wrong button.

**Comment by SveSop** [comment]
Hmm.. 2672f569cfe33fb6365f7a6eaa8fb6c7e1d84844 does not segfault for me if `nvapi.dll` is not available?

**Comment by jp7677** [comment]
Ok, sorry, in that case `GetProcAddress` seems to handles `nullptr` nicely and just returns `nullptr`.
Using `FreeLibrary` is still the better practice though with a loaded module, but probably wont make much difference in your case.
